title: royforge
logo: /assets/logo/royforge-logo.svg
author: ROYFORGE
email: royforge@gmail.com
description: > # this means to ignore newlines until "plugins:"
  Software projects, apps, articles, videos, tutorials, books forged 
  by Koyeli Roy and Pradyumna Roy (Prady Roy) on microservices, 
  reactive programming, devops, management and kids programming.

plugins:
 - jekyll-feed
 - jekyll-seo-tag

# Royforge date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
royforge:
  date_format: "%b %-d, %Y"
  # generate social links in footer
  social_links:
    github: royforge
    # rss: rss  
    facebook: royforge.in
    # instagram: royforge
    linkedin1: pradyroy
    linkedin2: koyeliroy
    # twitter: royforge
    # youtube: royforge
    youtube_channel: UCjKIkD8mJBomisa5Mp_3Kvw
    youtube_channel_name: royforge

# Use menu_navbar_auto.html in default.html, if you want to link only 
# specific pages in your header, uncomment below(header_pages) and add 
# the path to the pages in order as they should show up
#header_pages:
#  - index.md
#  - xyz.md

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up:
menu:
  - title: K-Blog
    url: https://medium.com/@koyeliroy
    image: /assets/img/koyeliroy-blog.jpg
  - title: P-Blog
    url: https://medium.com/@pradyroy
    image: /assets/img/pradyroy-blog.jpg
  - title: Koyeli
    url: https://koyeliroy.github.io
    image: /assets/img/koyeliroy-profile.jpg
  - title: Pradyumna (Prady)
    url: https://pradyroy.github.io
    image: /assets/img/pradyroy-profile.jpg
  - title: Apps
    url: /apps/
    image: /assets/img/royforge-apps.jpg
  - title: Projects  
    url: /projects/
    image: /assets/img/royforge-projects.jpg
  - title: Books
    url: /books/
    image: /assets/img/royforge-books.jpg
  - title: Vlog
    url: /vlog/
    image: /assets/img/royforge-videos.jpg